const terceiraListaCidades = [
    "Guarulhos",
    "Barueri",
    "Mauá",
    "Santo André",
    "São Bernardo do Campo",
    "Diadema",
    "São Caetano do Sul",
    "Osasco",
    "Carapicuíba",
    "Santana de Parnaíba",
    "Itapevi",
    "Jandira",
    "Embu das Artes",
    "Taboão da Serra",
    "Cotia",
    "São Paulo",
    "São Vicente",
    "Guarujá",
    "Santos",
    "Praia Grande",
    "Bertioga",
    "Cubatão",
    "São Sebastião",
    "Mongaguá",
    "Itanhaém",
    "Ilhabela",
    "Peruíbe",
    "Rio de Janeiro",
    "São Gonçalo",
    "Duque de Caxias",
    "Nova Iguaçu",
    "Niterói",
    "Belford Roxo",
    "São João de Meriti",
    "Campos dos Goytacazes",
    "Petrópolis",
    "Volta Redonda",
    "Magé",
    "Itaboraí",
    "Mesquita",
    "Nilópolis",
    "Maricá",
    "Queimados",
    "Nova Friburgo",
    "Teresópolis",
    "Barra Mansa",
    "Resende",
    "Barra do Piraí",
    "Valença",
    "Macaé",
    "Cabo Frio",
    "Rio das Ostras",
    "Armação dos Búzios",
    "Angra dos Reis",
    "Mangaratiba",
    "Paraty",
    "Niterói",
    "Petrópolis",
    "Teresópolis",
    "Nova Iguaçu",
    "Duque de Caxias",
    "Nilópolis",
    "Belford Roxo",
    "Mesquita",
    "Queimados",
    "São João de Meriti",
    "Itaboraí",
    "Maricá",
    "Rio Bonito",
    "Araruama",
    "Saquarema",
    "Cabo Frio",
    "São Pedro da Aldeia",
    "Casimiro de Abreu",
    "Tanguá",
    "Rio de Janeiro",
    "São Gonçalo",
    "Duque de Caxias",
    "Nova Iguaçu",
    "Niterói",
    "Belford Roxo",
    "São João de Meriti",
    "Mesquita",
    "Campos dos Goytacazes",
    "Petrópolis",
    "Volta Redonda",
    "Magé",
    "Itaboraí",
    "Nilópolis",
    "Macaé",
    "Angra dos Reis",
    "Nova Friburgo",
    "Barra Mansa",
    "Resende",
    "Teresópolis",
    "Araruama",
    "São Pedro da Aldeia",
    "Cabo Frio",
    "Itaguaí",
    "Maricá",
    "Queimados",
    "Rio das Ostras",
    "Mangaratiba",
    "Saquarema",
    "Seropédica",
    "Japeri",
    "Paracambi",
    "Guapimirim",
    "Cachoeiras de Macacu",
    "Rio Claro",
    "Areal",
    "Mendes",
    "Engenheiro Paulo de Frontin",
    "Vassouras",
    "Paty do Alferes",
    "Piraí",
    "Pinheiral",
    "Comendador Levy Gasparian",
    "Rio de Janeiro",
    "São Gonçalo",
    "Duque de Caxias",
    "Nova Iguaçu",
    "Niterói",
    "Belford Roxo",
    "São João de Meriti",
    "Mesquita",
    "Campos dos Goytacazes",
    "Petrópolis",
    "Volta Redonda",
    "Magé",
    "Itaboraí",
    "Nilópolis",
    "Macaé",
    "Angra dos Reis",
    "Nova Friburgo",
    "Barra Mansa",
    "Resende",
    "Teresópolis",
    "Araruama",
    "São Pedro da Aldeia",
    "Cabo Frio",
    "Itaguaí",
    "Maricá",
    "Queimados",
    "Rio das Ostras",
    "Mangaratiba",
    "Saquarema",
    "Seropédica",
    "Japeri",
    "Paracambi",
    "Guapimirim",
    "Cachoeiras de Macacu",
    "Rio Claro",
    "Areal",
    "Mendes",
    "Engenheiro Paulo de Frontin",
    "Vassouras",
    "Paty do Alferes",
    "Piraí",
    "Pinheiral",
    "Comendador Levy Gasparian",
    "Rio de Janeiro",
    "São Gonçalo",
    "Duque de Caxias",
    "Nova Iguaçu",
    "Niterói",
    "Belford Roxo",
    "São João de Meriti",
    "Mesquita",
    "Campos dos Goytacazes",
    "Petrópolis",
    "Volta Redonda",
    "Magé",
    "Itaboraí",
    "Nilópolis",
    "Macaé",
    "Angra dos Reis",
    "Nova Friburgo",
    "Barra Mansa",
    "Resende",
    "Teresópolis",
    "Araruama",
    "São Pedro da Aldeia",
    "Cabo Frio",
    "Itaguaí",
    "Maricá",
    "Queimados",
    "Rio das Ostras",
    "Mangaratiba",
    "Saquarema",
    "Seropédica",
    "Japeri",
    "Paracambi",
    "Guapimirim",
    "Cachoeiras de Macacu",
    "Rio Claro",
    "Areal",
    "Mendes",
    "Engenheiro Paulo de Frontin",
    "Vassouras",
    "Paty do Alferes",
    "Piraí",
    "Pinheiral",
    "Comendador Levy Gasparian" ];


const cidadesDeGoias = [
    "Goiânia",
    "Aparecida de Goiânia",
    "Anápolis",
    "Rio Verde",
    "Águas Lindas de Goiás",
    "Luziânia",
    "Valparaíso de Goiás",
    "Trindade",
    "Formosa",
    "Novo Gama",
    "Itumbiara",
    "Senador Canedo",
    "Catalão",
    "Jataí",
    "Planaltina",
    "Caldas Novas",
    "Santo Antônio do Descoberto",
    "Inhumas",
    "Morrinhos",
    "Goianésia",
    "Mineiros",
    "Quirinópolis",
    "Niquelândia",
    "Ceres",
    "Porangatu",
    "Jaraguá",
    "São Luís de Montes Belos",
    "Pires do Rio",
    "Bela Vista de Goiás",
    "Itapuranga",
    "Goianira",
    "Campinorte",
    "Cristalina",
    "Iporá",
    "Alexânia",
    "Palmeiras de Goiás",
    "Santo Antônio de Goiás",
    "Uruaçu",
    "Pontalina",
    "Goiatuba",
    "Alto Paraíso de Goiás",
    "Anicuns",
    "Buriti Alegre",
    "Padre Bernardo",
    "Aragoiânia",
    "Jussara",
    "Cachoeira Alta",
    "Caiapônia",
    "Santa Helena de Goiás",
    "Inaciolândia",
    "Campos Belos",
    "Piracanjuba",
    "Itaguaru",
    "Cavalcante",
    "Santa Terezinha de Goiás",
    "Cocalzinho de Goiás",
    "Caldazinha",
    "Itapirapuã",
    "Corumbaíba",
    "Anápolis",
    "Água Fria de Goiás",
    "Cristianópolis",
    "Nerópolis",
    "Damolândia",
    "Goianápolis",
    "Varjão",
    "Anhanguera",
    "Córrego do Ouro",
    "Araguapaz",
    "Divinópolis de Goiás",
    "Campestre de Goiás",
    "Doverlândia",
    "Itapaci",
    "Aloândia",
    "Crixás",
    "Aurilândia",
    "Águas Lindas de Goiás",
    "Carmo do Rio Verde",
    "Buritinópolis",
    "Abadiânia",
    "Aparecida de Goiás",
    "Arenópolis",
    "Cachoeira de Goiás",
    "Bom Jesus de Goiás",
    "Aurora do Norte",
    "Divinópolis de Goiás",
    "Americanas",
    "Anicuns",
    "Caiapônia",
    "Baliza" ];


const cidadesDeSaoPaulo = [
    "São Paulo",
    "Guarulhos",
    "Campinas",
    "São Bernardo do Campo",
    "São José dos Campos",
    "Santo André",
    "Ribeirão Preto",
    "Osasco",
    "Sorocaba",
    "Mauá",
    "São José do Rio Preto",
    "Mogi das Cruzes",
    "Diadema",
    "Jundiaí",
    "Piracicaba",
    "Carapicuíba",
    "Bauru",
    "Itaquaquecetuba",
    "São Vicente",
    "Santos",
    "Franca",
    "Praia Grande",
    "Taboão da Serra",
    "Sumaré",
    "Guarujá",
    "Suzano",
    "Barueri",
    "Taubaté",
    "Embu das Artes",
    "Presidente Prudente",
    "Marília",
    "São Carlos",
    "Jacareí",
    "Hortolândia",
    "Vinhedo",
    "Itapevi",
    "Americana",
    "Votuporanga",
    "Itu",
    "Catanduva",
    "Araçatuba",
    "Franco da Rocha",
    "Ferraz de Vasconcelos",
    "Indaiatuba",
    "São Caetano do Sul",
    "Botucatu",
    "Araraquara",
    "Cotia",
    "Rio Claro",
    "Mogi Guaçu",
    "Limeira",
    "Atibaia",
    "Avaré",
    "Tatuí",
    "Barretos",
    "Sertãozinho",
    "Ourinhos",
    "Pindamonhangaba",
    "Santa Bárbara d'Oeste",
    "Itapetininga",
    "Bragança Paulista",
    "Jaguariúna",
    "Jaú",
    "Leme",
    "Registro",
    "Campo Limpo Paulista",
    "Várzea Paulista",
    "Mairiporã",
    "Lençóis Paulista",
    "Salto",
    "Tupã",
    "Valinhos",
    "Itapeva",
    "Itapira",
    "Lorena",
    "Várzea Grande Paulista",
    "Araras",
    "Cubatão",
    "Barueri",
    "Mauá",
    "Carapicuíba",
    "São Caetano do Sul",
    "Itapecerica da Serra",
    "Cotia",
    "Ferraz de Vasconcelos",
    "Francisco Morato",
    "Itatiba",
    "Suzano",
    "Itaquaquecetuba",
    "Mogi Guaçu",
    "Itapira",
    "Salto",
    "Tatuí",
    "Vinhedo",
    "Valinhos",
    "Louveira",
    "Itupeva",
    "Jarinu",
    "Hortolândia",
    "Santa Bárbara d'Oeste",
    "Americana",
    "Limeira",
    "Rio Claro",
    "Piracicaba",
    "São Pedro",
    "Jundiaí",
    "Indaiatuba",
    "Valinhos",
    "Atibaia",
    "Bragança Paulista",
    "Amparo",
    "Jarinu",
    "São Roque",
    "Itu",
    "Cabreúva",
    "Itapevi",
    "Barueri",
    "Santana de Parnaíba",
    "Taboão da Serra",
    "Embu das Artes",
    "Itapecerica da Serra",
    "Embu-Guaçu",
    "Cotia",
    "Vargem Grande Paulista",
    "Jandira",
    "Carapicuíba",
    "Osasco",
    "Barueri",
    "Taboão da Serra",
    "Itapecerica da Serra",
    "Embu das Artes",
    "Carapicuíba",
    "São Lourenço da Serra",
    "Vargem Grande Paulista",
    "Cotia",
    "Itapevi",
    "Jandira",
    "Itapevi",
    "Jandira",
    "Barueri",
    "Carapicuíba",
    "Santana de Parnaíba",
    "Embu das Artes",
    "Osasco",
    "Barueri",
    "Osasco",
    "Barueri",
    "Osasco",
    "Barueri",
    "Itapevi",
    "Itapevi",
    "Cotia",
    "Cotia",
    "Itapevi",
    "Jandira",
    "São Paulo",
    "Guarulhos",
    "Campinas",
    "São Bernardo do Campo",
    "São José dos Campos",
    "Santo André",
    "Ribeirão Preto",
    "Osasco",
    "Sorocaba",
    "Mauá",
    "São José do Rio Preto",
    "Mogi das Cruzes",
    "Diadema",
    "Jundiaí",
    "Piracicaba",
    "Carapicuíba",
    "Bauru",
    "Itaquaquecetuba",
    "São Vicente",
    "Santos",
    "Franca",
    "Praia Grande",
    "Taboão da Serra",
    "Sumaré",
    "Guarujá",
    "Suzano",
    "Barueri",
    "Taubaté",
    "Embu das Artes",
    "Presidente Prudente",
    "Marília",
    "São Carlos",
    "Jacareí",
    "Hortolândia",
    "Vinhedo",
    "Itapevi",
    "Americana",
    "Votuporanga",
    "Itu",
    "Catanduva",
    "Araçatuba",
    "Franco da Rocha",
    "Ferraz de Vasconcelos",
    "Indaiatuba",
    "São Caetano do Sul",
    "Botucatu",
    "Araraquara",
    "Cotia",
    "Rio Claro",
    "Mogi Guaçu",
    "Limeira",
    "Atibaia",
    "Avaré",
    "Tatuí",
    "Barretos",
    "Sertãozinho",
    "Ourinhos",
    "Pindamonhangaba",
    "Santa Bárbara d'Oeste",
   
const cidadesDeMatoGrosso = [
    "Cuiabá",
    "Várzea Grande",
    "Rondonópolis",
    "Sinop",
    "Tangará da Serra",
    "Cáceres",
    "Sorriso",
    "Lucas do Rio Verde",
    "Primavera do Leste",
    "Barra do Garças",
    "Nova Mutum",
    "Pontes e Lacerda",
    "Alta Floresta",
    "Campo Verde",
    "Juína",
    "Colniza",
    "Guarantã do Norte",
    "Peixoto de Azevedo",
    "Juara",
    "Barra do Bugres",
    "Colíder",
    "Rondonópolis",
    "Poxoréu",
    "Campo Verde",
    "Rosário Oeste",
    "São Félix do Araguaia",
    "Vila Bela da Santíssima Trindade",
    "Diamantino",
    "Nortelândia",
    "Porto Alegre do Norte",
    "Araguaiana",
    "Nova Olímpia",
    "Arenápolis",
    "Alto Paraguai",
    "Jaciara",
    "Vale de São Domingos",
    "Nova Bandeirantes",
    "Nova Brasilândia",
    "Cláudia",
    "Nova Canaã do Norte",
    "Comodoro",
    "Nova Xavantina",
    "Vila Rica",
    "Nova Guarita",
    "Novo Horizonte do Norte",
    "Querência",
    "Nova Ubiratã",
    "Santo Antônio do Leste",
    "Campinápolis",
    "Santa Rita do Trivelato",
    "Itanhangá",
    "Nova Marilândia",
    "Nova Maringá",
    "Gaúcha do Norte",
    "Cocalinho",
    "Guiratinga",
    "Nova Santa Helena",
    "Nova Nazaré",
    "Lambari D'Oeste",
    "Sapezal",
    "Curvelândia",
    "Porto Estrela",
    "Serra Nova Dourada",
    "Nova Lacerda",
    "Indiavaí",
    "Porto Esperidião",
    "Araputanga",
    "Ribeirãozinho",
    "Castanheira",
    "Nossa Senhora do Livramento",
    "Nova Monte Verde",
    "Nova Brasilândia",
    "Paranaíta",
    "Figueirópolis D'Oeste",
    "Ponte Branca",
    "Reserva do Cabaçal",
    "Novo São Joaquim",
    "Ponte Branca",
    "Porto dos Gaúchos",
    "São José do Povo",
    "Juruena",
    "Santa Terezinha",
    "Nova Canaã do Norte",
    "Aripuanã",
    "Nova Ubiratã",
    "Santo Antônio de Leverger",
    "São José do Xingu",
    "Vale de São Domingos",
    "Santa Cruz do Xingu",
    "Barão de Melgaço",
    "Planalto da Serra",
    "Porto Alegre do Norte",
    "Santo Antônio do Leste",
    "São José do Povo" ];



const cidadesDeMatoGrossoDoSul = [
    "Campo Grande",
    "Dourados",
    "Três Lagoas",
    "Corumbá",
    "Ponta Porã",
    "Naviraí",
    "Nova Andradina",
    "Aquidauana",
    "Sidrolândia",
    "Paranaíba",
    "Amambai",
    "Maracaju",
    "Rio Brilhante",
    "Coxim",
    "Caarapó",
    "Miranda",
    "Ladário",
    "Jardim",
    "Bataguassu",
    "Bonito",
    "Terenos",
    "Bela Vista",
    "Fátima do Sul",
    "Ivinhema",
    "Itaporã",
    "Dois Irmãos do Buriti",
    "Angélica",
    "Sete Quedas",
    "Cassilândia",
    "Nova Alvorada do Sul",
    "Porto Murtinho",
    "Anastácio",
    "Inocência",
    "Rio Verde de Mato Grosso",
    "Aparecida do Taboado",
    "São Gabriel do Oeste",
    "Bodoquena",
    "Batayporã",
    "Sonora",
    "Itaquiraí",
    "Taquarussu",
    "Paranhos",
    "Deodápolis",
    "Selvíria",
    "Tacuru",
    "Alcinópolis",
    "Corguinho",
    "Jateí",
    "Jaraguari",
    "Santa Rita do Pardo" ];




 acre: [
    'Rio Branco',
    'Cruzeiro do Sul',
    'Senador Guiomard',
    'Feijó',
    'Tarauacá',
    'Brasiléia',
    'Plácido de Castro',
    'Xapuri',
    'Manoel Urbano',
    'Marechal Thaumaturgo',
    'Porto Walter',
    'Assis Brasil',
    'Capixaba',
    'Porto Acre',
    'Epitaciolândia',
    'Sena Madureira',
    'Santa Rosa do Purus',
    'Bujari',
    'Jordão',
    'Acrelândia',
    'Rodrigues Alves',
    'Mâncio Lima',
    'Cantá',
    'Cruzeiro do Sul',
    'Senador Guiomard',
    'Feijó',
    'Tarauacá',
    'Brasiléia',
    'Plácido de Castro',
    'Xapuri',
    'Manoel Urbano',
    'Marechal Thaumaturgo',
    'Porto Walter',
    'Assis Brasil',
    'Capixaba',
    'Porto Acre',
    'Epitaciolândia',
    'Sena Madureira',
    'Santa Rosa do Purus',
    'Bujari',
    'Jordão',
    'Acrelândia',
    'Rodrigues Alves',
    'Mâncio Lima',
    'Cantá',
    'Cruzeiro do Sul',
    'Senador Guiomard',
    'Feijó',
    'Tarauacá',
    'Brasiléia',
    'Plácido de Castro',
    'Xapuri',
    'Manoel Urbano',
    'Marechal Thaumaturgo',
    'Porto Walter',
    'Assis Brasil',
    'Capixaba',
    'Porto Acre',
    'Epitaciolândia',
    'Sena Madureira',
    'Santa Rosa do Purus',
    'Bujari',
    'Jordão',
    'Acrelândia',
    'Rodrigues Alves',
    'Mâncio Lima',
    'Cantá',
    'Cruzeiro do Sul',
    'Senador Guiomard',
    'Feijó',
    'Tarauacá',
    'Brasiléia',
    'Plácido de Castro',
    'Xapuri',
    'Manoel Urbano',
    'Marechal Thaumaturgo',
    'Porto Walter',
    'Assis Brasil',
    'Capixaba',
    'Porto Acre',
    'Epitaciolândia',
    'Sena Madureira',
    'Santa Rosa do Purus',
    'Bujari',
    'Jordão',
    'Acrelândia',
    'Rodrigues Alves',
    'Mâncio Lima',
    'Cantá' ]

 alagoas: [
    'Maceió',
    'Arapiraca',
    'Rio Largo',
    'Palmeira dos Índios',
    'Penedo',
    'União dos Palmares',
    'São Miguel dos Campos',
    'Campo Alegre',
    'Delmiro Gouveia',
    'Coruripe',
    'Santana do Ipanema',
    'Maragogi',
    'Pilar',
    'Viçosa',
    'Girau do Ponciano',
    'São Luís do Quitunde',
    'São Sebastião',
    'Atalaia',
    'Marechal Deodoro',
    'Boca da Mata',
    'São José da Laje',
    'Igreja Nova',
    'Porto Calvo',
    'Olho d\'Água das Flores',
    'Piranhas',
    'São José da Tapera',
    'Teotônio Vilela',
    'São Miguel dos Campos',
    'Campo Alegre',
    'Delmiro Gouveia',
    'Coruripe',
    'Santana do Ipanema',
    'Maragogi',
    'Pilar',
    'Viçosa',
    'Girau do Ponciano',
    'São Luís do Quitunde',
    'São Sebastião',
    'Atalaia',
    'Marechal Deodoro',
    'Boca da Mata',
    'São José da Laje',
    'Igreja Nova',
    'Porto Calvo',
    'Olho d\'Água das Flores',
    'Piranhas',
    'São José da Tapera',
    'Teotônio Vilela',
    'São Miguel dos Campos',
    'Campo Alegre',
    'Delmiro Gouveia',
    'Coruripe',
    'Santana do Ipanema',
    'Maragogi',
    'Pilar',
    'Viçosa',
    'Girau do Ponciano',
    'São Luís do Quitunde',
    'São Sebastião',
    'Atalaia',
    'Marechal Deodoro',
    'Boca da Mata',
    'São José da Laje',
    'Igreja Nova',
    'Porto Calvo',
    'Olho d\'Água das Flores',
    'Piranhas',
    'São José da Tapera',
    'Teotônio Vilela' ]


 amazonas: [
    'Manaus',
    'Parintins',
    'Itacoatiara',
    'Manacapuru',
    'Coari',
    'Tefé',
    'Tabatinga',
    'Humaitá',
    'Maués',
    'São Gabriel da Cachoeira',
    'Borba',
    'Benjamin Constant',
    'Manicoré',
    'Autazes',
    'Barreirinha',
    'Boca do Acre',
    'Careiro',
    'Eirunepé',
    'Iranduba',
    'Manacapuru',
    'Nova Olinda do Norte',
    'São Paulo de Olivença',
    'Tabatinga',
    'Urucurituba',
    'Beruri',
    'Maraã',
    'Silves',
    'Uarini',
    'Alvarães',
    'Anamã',
    'Anori',
    'Autazes',
    'Barreirinha',
    'Boca do Acre',
    'Careiro',
    'Eirunepé',
    'Iranduba',
    'Manacapuru',
    'Nova Olinda do Norte',
    'São Paulo de Olivença',
    'Tabatinga',
    'Urucurituba',
    'Beruri',
    'Maraã',
    'Silves',
    'Uarini',
    'Alvarães',
    'Anamã',
    'Anori',
    'Autazes',
    'Barreirinha',
    'Boca do Acre',
    'Careiro',
    'Eirunepé',
    'Iranduba',
    'Manacapuru',
    'Nova Olinda do Norte',
    'São Paulo de Olivença',
    'Tabatinga',
    'Urucurituba',
    'Beruri',
    'Maraã',
    'Silves',
    'Uarini',
    'Alvarães',
    'Anamã',
    'Anori' ],
    

    let nomes =
    ["Maria", "João", "Ana", "Pedro", "Luiza", "Carlos", "Isabela", "Rafael",
    "Camila", "Lucas", "Mariana", "Fernando", "Juliana", "Gabriel", "Larissa",
    "Diego", "Patrícia", "Gustavo", "Natália", "Felipe", "Amanda", "Rodrigo",
    "Carolina", "Daniel", "Sara", "Thiago", "Laura", "Luciana", "Vinícius", "Beatriz",
    "Ricardo", "Helena", "Rafaela", "Júlio", "Débora", "Marcelo", "Eduarda", "Antônio",
    "Bianca", "Leonardo", "Alice", "Paulo", "Manuela", "André", "Valentina", "Renato",
    "Clara", "Bruno", "Cristina", "Miguel", "Tatiana", "José", "Carla", "Fábio",
    "Elisa", "Marcos", "Patricia", "Thiago", "Gisele", "Joana", "Vitor", "Mariane",
    "Roberto", "Talita", "Giovanni", "Laís", "Raul", "Marina", "Hugo", "Erika",
    "Diego", "Fernanda", "Igor", "Vanessa", "Cesar", "Nathalia", "Alexandre",
    "Verônica", "Rafael", "Bárbara", "Sérgio", "Cintia", "Ricardo", "Lorena",
    "Felipe", "Carolina", "Caio", "Lívia", "Henrique", "Isadora", "Matheus", "Mirela",
    "Vitor", "Aline", "Samuel", "Thais", "Lucas", "Renata", "Anderson", "Gabriela",
    "Cauê", "Julia", "Davi", "Fernanda", "Vinicius", "Tatiane", "Leandro", "Márcia",
    "Alex", "Monica", "Eduardo", "Juliana", "Guilherme", "Vanessa", "Wagner",
    "Cristiane", "Marcelo", "Larissa", "Hélio", "Amanda", "Fernando", "Raquel",
    "Marcelo", "Luana", "Rodrigo", "Jéssica", "André", "Andressa", "Luiz", "Juliana",
    "Felipe", "Larissa", "Rafael", "Patrícia", "Paulo", "Luciana", "José", "Carolina",
    "Bruno", "Mariana", "Gustavo", "Thaís", "Ricardo", "Aline", "Thiago", "Renata",
    "Antônio", "Camila", "Leonardo", "Isabela", "Miguel", "Gabriela", "Raul",
    "Letícia", "Cesar", "Tatiana", "Marcos", "Priscila", "Igor", "Bianca", "Rafael",
    "Natália", "Sérgio", "Amanda", "Caio", "Fernanda", "Henrique", "Gisele", "Matheus",
    "Carla", "Vitor", "Erika", "Samuel", "Larissa", "Anderson", "Elaine", "Cauê",
    "Mirela", "Davi", "Vanessa", "Vinicius", "Marina", "Leandro", "Bárbara", "Alex",
    "Verônica", "Eduardo", "Lorena", "Guilherme", "Nathalia", "Wagner", "Isadora",
    "Hélio", "Lívia"];

 

const cidadesBrasil = [
  "São Paulo",
  "Rio de Janeiro",
  "Belo Horizonte",
  "Salvador",
  "Brasília",
  "Curitiba",
  "Porto Alegre",
  "Fortaleza",
  "Recife",
  "Goiânia",
  "Manaus",
  "Belém",
  "São Luís",
  "Campo Grande",
  "Cuiabá",
  "Natal",
  "Teresina",
  "João Pessoa",
  "Aracaju",
  "Maceió",
  "Palmas",
  "Vitória",
  "Florianópolis",
  "Porto Velho",
  "Boa Vista",
  "Macapá",
  "Rio Branco",
  "São José dos Campos",
  "Campinas",
  "Ribeirão Preto",
  "Sorocaba",
  "Santo André",
  "São Bernardo do Campo",
  "São Caetano do Sul",
  "Diadema",
  "Osasco",
  "Barueri",
  "Santos",
  "Guarujá",
  "São Vicente",
  "Mogi das Cruzes",
  "Itaquaquecetuba",
  "Suzano",
  "Taboão da Serra",
  "Embu das Artes",
  "Itapevi",
  "Jandira",
  "Barueri",
  "Carapicuíba",
  "Cotia",
  "Vargem Grande Paulista",
  "Arujá",
  "Poá",
  "Ferraz de Vasconcelos",
  "Mauá",
  "Ribeirão Pires",
  "Rio Grande da Serra",
  "Salesópolis",
  "Santa Isabel",
  "Ferraz de Vasconcelos",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Bertioga",
  "Guarujá",
  "Praia Grande",
  "Mongaguá",
  "Itanhaém",
  "Peruíbe",
  "São Vicente",
  "Santos",
  "Cubatão",
  "São José dos Campos",
  "Jacareí",
  "Caçapava",
  "Taubaté",
  "Pindamonhangaba",
  "Guaratinguetá",
  "Lorena",
  "Cruzeiro",
  "Aparecida",
  "Caraguatatuba",
  "Ubatuba",
  "Campos do Jordão",
  "São Sebastião",
  "Ilhabela",
  "Caraguatatuba",
  "Ubatuba",
  "Berti"]

